# Example funding file for HACS support
# See https://hacs.xyz/docs/publish/include#repository-structure
# Add your funding links below
# github: ["your_github_username"]
# patreon: ["your_patreon_username"]
# ko_fi: ["your_kofi_username"]
